# Матрицы и матричные операции. Часть 1

In [2]:
import numpy as np

__1.__ Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

а)  A  — матрица  4×2 ,  B  — матрица  4×2 ;

б)  A  — матрица  2×5 ,  B  — матрица  5×3 ;

в)  A  — матрица  8×3 ,  B  — матрица  3×8 ;

г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4 .

a) AB -, BA -; <br>
б) AB 2×3, BA -; <br>
в) AB 8×8, BA 3×3; <br>
г) AB 4×4, BA 4×4.

__2.__ Найдите сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$$A+B=\begin{pmatrix}
5 & 2\\ 
0 & 0
\end{pmatrix}$$

$$A\cdot B=\begin{pmatrix}
1\cdot4+(-2)\cdot0 & 1\cdot(-1)+(-2)\cdot5\\ 
3\cdot4+0\cdot0 & 3\cdot(-1)+0\cdot5
\end{pmatrix}=\begin{pmatrix}
4 & -11\\ 
12 & -3 
\end{pmatrix}.$$

In [3]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$$3A-2B+4C=3\cdot\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}-2\cdot\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}+4\cdot\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}=\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}.$$

In [4]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица C\n{C}')
print(f'Матрица 3𝐴−2𝐵+4𝐶\n{3*A-2*B+4*C}')

Матрица A
[[ 1  7]
 [ 3 -6]]
Матрица B
[[ 0  5]
 [ 2 -1]]
Матрица C
[[ 2 -4]
 [ 1  1]]
Матрица 3𝐴−2𝐵+4𝐶
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.

$$A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}.$$

$$A^{T}A=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}\cdot\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$$

$$AA^{T}=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}\cdot\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}=\begin{pmatrix}
4\cdot4+1\cdot1 & 4\cdot5+1\cdot(-2) & 4\cdot2+1\cdot3\\ 
5\cdot4+(-2)\cdot1 & 5\cdot5+(-2)\cdot(-2) & 5\cdot2+(-2)\cdot3\\ 
2\cdot4+3\cdot1 & 2\cdot5+3\cdot(-2) & 2\cdot2+3\cdot3
\end{pmatrix}=\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}.$$

$$A^{T}A=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}\cdot\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}=\begin{pmatrix}
4\cdot4+5\cdot5+2\cdot2 & 4\cdot1+5\cdot(-2)+2\cdot3\\ 
1\cdot4+(-2)\cdot5+3\cdot2 & 1\cdot1+(-2)\cdot(-2)+3\cdot3
\end{pmatrix}=\begin{pmatrix}
45 & 0 \\ 
0 & 14
\end{pmatrix}.$$

In [5]:
A = np.array([[4, 1], [5, -2], [2, 3]])
At = np.array([[4, 5, 2], [1, -2, 3]])

print(f'Матрица A\n{A}')
print(f'Матрица At\n{B}')
print(f'Матрица AAt\n{np.dot(A, At)}')
print(f'Матрица AAt\n{np.dot(At, A)}')

Матрица A
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Матрица At
[[ 0  5]
 [ 2 -1]]
Матрица AAt
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица AAt
[[45  0]
 [ 0 14]]


5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [6]:
A = np.array([[4, 1, 5, 15], [5, -2, 8, -7], [2, 3, 9, -6]])
B = np.array([[4, 5, 2, 9], [1, -2, 3, -7], [2, 3, -1, 9], [1, 1, 3, 4]])
print(A)
print(B)
print(A@B)

[[ 4  1  5 15]
 [ 5 -2  8 -7]
 [ 2  3  9 -6]]
[[ 4  5  2  9]
 [ 1 -2  3 -7]
 [ 2  3 -1  9]
 [ 1  1  3  4]]
[[ 42  48  51 134]
 [ 27  46 -25 103]
 [ 23  25 -14  54]]


In [7]:
def mult_AB(A, B):
    # получение итоговых элементов для целевой матрицы произведения AB
    ab = [] # переменная для записи итоговых элементов для целевой матрицы (последовательность элементов нарушена: сверху вниз)
    n = 0 # столбец в матрице В
    while n < B.shape[1]:
        for i in A:
            m = 0 # строка в матрице В
            r = [] # список произведений одного элемента из матрицы А на другой элемент из матрицы В, из которого состоит один элемент итоговой матрицы
            for j in i:
                k = j*B[m,n]
                m = m + 1
                r.append(k)
            sum_r = 0 # один элемент из итоговой матрицы, т.е. сумма произведений из r
            for el in r:
                sum_r += el  
            ab.append(sum_r)
        n = n + 1
    # изменение последовательности элементов и разбиение общего списка на несколько списков
    q = 0 # индекс элемента в получившемся списке ab
    AB = [] # целевой список списков
    while q < A.shape[0]:
        s = [] # строка целевой матрицы
        while q < len(ab):
            s.append(ab[q])
            q += A.shape[0]
        s = str(s).replace(',', '')
        AB.append(s)
        q = q - (len(ab) - 1)
    AB = "\n".join(AB)
    print(AB)
mult_AB(A, B)

[42 48 51 134]
[27 46 -25 103]
[23 25 -14 54]


# Матрицы и матричные операции. Часть 2

__1.__ Вычислите определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$



а) $$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}=
=(sinx\cdot sinx+cosx\cdot cosx)=sinx^2+cosx^2=1;$$

б) $$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}=4\cdot5\cdot9=180;$$

In [17]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}.')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
1440.


в) $$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}=
1\cdot\begin{vmatrix}
5 & 6\\ 
8 & 9
\end{vmatrix}-
2\cdot\begin{vmatrix}
4 & 6\\ 
7 & 9
\end{vmatrix}+
3\cdot\begin{vmatrix}
4 & 5\\ 
7 & 8
\end{vmatrix}=1\cdot(5\cdot9-8\cdot6)-2\cdot(4\cdot9-6\cdot7)+3\cdot(4\cdot8-5\cdot7)= \\
=-3+12-9=0;$$

In [13]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}.')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
0.



__2.__ Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   


а) $det(A^{2}) = detA\cdot detA = 4\cdot4 = 16$;

б) $det(A^{T}) = detA = 4;$

в) $det(2A) = 2^n\cdot detA = 2^n\cdot4 = 2^n\cdot4$, где n - количество строк/столбцов матрицы А.

__3.__  Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Умножим первую строку матрицы на 2 и сложим со второй строкой.

$$\begin{pmatrix}
-2 & 7 & -3\\ 
0 & 0 & 0\\ 
-3 & 7 & 13
\end{pmatrix}$$

Матрица перестала быть квадратной и ее определитель будет равен 0. Значит она вырожденная.

__4.__ Найдите ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

а) Если сложить первые две строки матрицы, умножить на минус 1 и сложить с третьей, то третья строка занулится. Между первыми двумя строками линейной зависимости нет, значит ранг матрицы равен 2.

In [23]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
np.linalg.matrix_rank(a)

2

б) Если сложить первые две строки матрицы, умножить на минус 1 и сложить с третьей, то третья строка занулится. Далее вторую строку умножим на -1 и сложим с первой т получим матрицу следующего вида:

$\begin{pmatrix}
0 & 0 & 0 & -1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Матрица 3 порядка.

In [22]:
a = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(a)

3